In [2]:
# import libraries
import pandas as pd
import seaborn as sns

In [3]:
# read in dataframe, let's us see the data that's been imported
df = pd.read_csv("planets.csv")

In [ ]:
# Surace-Level Familiarity 

# How many rows and columns?
rowNum = 0
colNum = 0
print(f"These are the row labels:\n {df.index}\nThese are the column labels:\n {df.columns}")

# find out the number
for rows in df.index:
    rowNum += 1
for col in df.columns:
    colNum += 1

print(f"\nThere are {rowNum} rows and {colNum} columns.")

These are the row labels:
 RangeIndex(start=0, stop=8, step=1)
These are the column labels:
 Index(['Planet', 'Color', 'Mass (10^24kg)', 'Diameter (km)',
       'Density (kg/m^3)', 'Surface Gravity(m/s^2)', 'Escape Velocity (km/s)',
       'Rotation Period (hours)', 'Length of Day (hours)',
       'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)',
       'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (degrees)',
       'Orbital Eccentricity', 'Obliquity to Orbit (degrees)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?', 'Surface Temperature (C)',
       'Atmospheric Composition', 'Atmospheric Pressure (bars)',
       'Surface Features', 'Composition'],
      dtype='object')

There are 8 rows and 27 columns

#### Verdict: The columns represent different aspects of all the planets. The names are specific, clean and readable. Nothing looks awkward or weird at a glance. Datatypes can be assumed.

In [ ]:
# now let's get the shape
df.shape
# I now see that this is a simpler way to get the number of rows and columns. I got a bit ahead of myself when doing the for loops before. Oopsie haha.

(8, 27)

In [19]:
# check for missing values w/ isna()
df.isna()

,Planet,Color,Mass (10^24kg),Diameter (km),Density (kg/m^3),Surface Gravity(m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),...,Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Surface Temperature (C),Atmospheric Composition,Atmospheric Pressure (bars),Surface Features,Composition
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

#### No missing values

In [20]:
# check for duplicated rows
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

#### No duplicate rows

In [21]:
# data type checking
df.dtypes

Planet                            object
Color                             object
Mass (10^24kg)                   float64
Diameter (km)                      int64
Density (kg/m^3)                   int64
Surface Gravity(m/s^2)           float64
Escape Velocity (km/s)           float64
Rotation Period (hours)          float64
Length of Day (hours)            float64
Distance from Sun (10^6 km)      float64
Perihelion (10^6 km)             float64
Aphelion (10^6 km)               float64
Orbital Period (days)             object
Orbital Velocity (km/s)          float64
Orbital Inclination (degrees)    float64
Orbital Eccentricity             float64
Obliquity to Orbit (degrees)     float64
Mean Temperature (C)               int64
Surface Pressure (bars)           object
Number of Moons                    int64
Ring System?                      object
Global Magnetic Field?            object
Surface Temperature (C)           object
Atmospheric Composition           object
Atmospheric Pressure (bars)       object
Surface Features                  object
Composition                       object
dtype: object

#### a lot of the descriptive factors that I thought would be strings are actually objects. numeric classes are all numeric, but whether they are ints or floats would require manually going through and using finding a reasoning for why they were labelled as such.